/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastic.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class SearchTest {
    @Test
    public void testAppHasAGreeting() {
//        Search classUnderTest = new Search();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
