/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastictweets;

import dagger.BindsInstance;
import dagger.Component;

import javax.inject.Inject;
import javax.inject.Singleton;

public class Index {
    private final elastictweets.twitterstream.TweetStreamer tweetStreamer;

    @Inject
    public Index(elastictweets.twitterstream.TweetStreamer tweetStreamer){
        this.tweetStreamer = tweetStreamer;
    }

    private void start() {
        tweetStreamer.listen();
    }

    public static void main(String[] args) {
        String tweetFilter = "uva";
        if (args.length == 1) {
            tweetFilter = args[0];
        }

        DaggerIndex_App.builder()
            .tweetFilter(tweetFilter)
            .build()
            .index()
            .start();
    }

    @Singleton
    @Component(modules = {
        elastictweets.twitterstream.TweetStreamer.RequestModule.class,
    })
    interface App {
        Index index();

        @Component.Builder
        interface Builder {
            @BindsInstance
            Builder tweetFilter(@elastictweets.util.TweetFilter String tweetFilter);
            App build();
        }
    }
}
