/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastictweets;

import dagger.BindsInstance;
import dagger.Component;
import elastictweets.domain.Tweet;
import elastictweets.services.Searcher;
import elastictweets.util.RequestScope;

import javax.inject.Inject;

public class Search {
    private final Searcher<Tweet> searcher;

    @Inject
    public Search(Searcher<Tweet> searcher) {
        this.searcher = searcher;
    }

    private void run(String input) {
        searcher.search(input).forEach(System.out::println);
    }

    public static void main(String[] args) {
        String query = "uva";
        if (args.length == 1) {
            query = args[0];
        }
        try (elastictweets.util.Closer closer = new elastictweets.util.Closer()) {
            DaggerSearch_App.builder()
                .closer(closer)
                .build()
                .search()
                .run(query);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @RequestScope
    @Component(modules = {
        elastictweets.elastic.ElasticModule.class,
    })
    interface App {
        Search search();

        @Component.Builder
        interface Builder {
            @BindsInstance Builder closer(elastictweets.util.Closer closer);
            App build();
        }
    }
}
