package(default_visibility = ["//visibility:public"])

java_library(
    name = "util",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/elastictweets/domain:domain",
        "//thirdparty:dagger",
        "//thirdparty:elasticsearch",
        "//thirdparty:gson",
        "//thirdparty:javax-inject",
    ],
)