/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastic.demo;

import elastic.index.ConfigurationSupplier;
import elastic.index.TweetStreamer;

public class Index {
    private final TweetStreamer tweetStreamer;

    public Index(TweetStreamer tweetStreamer){
        this.tweetStreamer = tweetStreamer;
    }

    private void start() {
        tweetStreamer.listen();
    }

    public static void main(String[] args) {
        String tweetFilter = "uva";
        if (args.length == 1) {
            tweetFilter = args[0];
        }
        TweetStreamer tweetStreamer =
            new TweetStreamer(new ConfigurationSupplier().get(), tweetFilter);
        Index index = new Index(tweetStreamer);
        index.start();
    }
}
