/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastic.demo;

import dagger.BindsInstance;
import dagger.Component;
import elastic.domain.Tweet;
import elastic.elastic.ElasticModule;
import elastic.services.Searcher;
import elastic.util.Closer;
import elastic.util.GsonModule;
import elastic.util.RequestScope;

import javax.inject.Inject;

public class Search {
    private final Searcher<Tweet> searcher;

    @Inject
    public Search(Searcher<Tweet> searcher) {
        this.searcher = searcher;
    }

    private void run(String input) {
        searcher.search(input).forEach(System.out::println);
    }

    public static void main(String[] args) {
        String query = "uva";
        if (args.length == 1) {
            query = args[0];
        }
        try (Closer closer = new Closer()) {
            DaggerSearch_App.builder()
                .closer(closer)
                .build()
                .search()
                .run(query);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @RequestScope
    @Component(modules = {
        ElasticModule.class,
    })
    interface App {
        Search search();

        @Component.Builder
        interface Builder {
            @BindsInstance Builder closer(Closer closer);
            App build();
        }
    }
}
