/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elastic.demo;

import elastic.search.Searcher;
import org.apache.http.HttpHost;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestClientBuilder;
import org.elasticsearch.client.RestHighLevelClient;

import java.io.IOException;
import java.util.List;

public class Search {
    public List<String> performSearch(String query) {
        RestClientBuilder restBuilder =
            RestClient.builder(new HttpHost("localhost", 9200));
        try (RestHighLevelClient client = new RestHighLevelClient(restBuilder)) {
            return new Searcher(client).search(query);
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }

    public static void main(String[] args) {
        String query = "uva";
        if (args.length == 1) {
            query = args[0];
        }
        Search search = new Search();
        search.performSearch(query).forEach(System.out::println);
    }
}
